### PR TITLE
[Don't merge] add jobs

### PR DESCRIPTION
**Pull request by nolastan**
Hey, it would be great to add job titles!

It looks like the API requires a list ID, so I left those as @TODO.

The companies are Fortune 500 and and the positions are from http://www.careerplanner.com/ListOfJobs.cfm

### CODE REVIEW

**Comment by keitharm** [comment]
That sounds like a cool idea.
I'll need to comb through the list though so that specific jobs like "United States Steel Corporation" couldn't appear for FR.

**Comment by nolastan** [comment]
I've only added this list to the US locale, so is that necessary?

**Comment by keitharm** [comment]
If possible, we want to keep the fields consistent across the different nationalities.

**Comment by brutalhonesty** [comment]
I would love to see this added as well!
:+1: 

Something such as:
```json
{
  "job": {
    "company": "Company Name",
    "occupancy": "My Job",
    "category": "My Category"
  }
}
```
Where category is one of the following:

```json
{
     "1103":"Actor/Director",
     "1105":"Movie",
     "1108":"Producer",
     "1109":"Writer",
     "1110":"Studio",
     "1111":"Movie Theater",
     "1112":"TV/Movie Award",
     "1113":"Fictional Character",
     "1200":"Album",
     "1201":"Song",
     "1202":"Musician/Band",
     "1204":"Musical Instrument",
     "1206":"Playlist",
     "1207":"Music Video",
     "1208":"Concert Tour",
     "1209":"Concert Venue",
     "1210":"Radio Station",
     "1211":"Record Label",
     "1212":"Music Award",
     "1213":"Music Chart",
     "1300":"Book",
     "1301":"Author",
     "1305":"Book Store",
     "1306":"Library",
     "1307":"Magazine",
     "1308":"Editor",
     "1400":"TV Show",
     "1402":"TV Network",
     "1404":"TV Channel",
     "1600":"Athlete",
     "1601":"Artist",
     "1602":"Public Figure",
     "1604":"Journalist",
     "1605":"News Personality",
     "1606":"Chef",
     "1607":"Lawyer",
     "1608":"Doctor",
     "1609":"Business Person",
     "1610":"Comedian",
     "1611":"Entertainer",
     "1612":"Monarch",
     "1613":"Teacher",
     "1614":"Dancer",
     "1700":"Politician",
     "1701":"Government Official",
     "1800":"Sports League",
     "1801":"Professional Sports Team",
     "1802":"Coach",
     "1803":"Amateur Sports Team",
     "1804":"School Sports Team",
     "1900":"Restaurant/Cafe",
     "2100":"Bar",
     "2101":"Club",
     "2200":"Company",
     "2201":"Product/Service",
     "2202":"Website",
     "2205":"Cars",
     "2206":"Bags/Luggage",
     "2208":"Camera/Photo",
     "2209":"Clothing",
     "2210":"Computers",
     "2211":"Software",
     "2212":"Office Supplies",
     "2213":"Electronics",
     "2214":"Health/Beauty",
     "2215":"Appliances",
     "2216":"Building Materials",
     "2217":"Commercial Equipment",
     "2218":"Home Decor",
     "2219":"Furniture",
     "2220":"Household Supplies",
     "2221":"Kitchen/Cooking",
     "2222":"Patio/Garden",
     "2223":"Tools/Equipment",
     "2224":"Wine/Spirits",
     "2226":"Jewelry/Watches",
     "2227":"Movies/Music",
     "2230":"Pet Supplies",
     "2231":"Outdoor Gear/Sporting Goods",
     "2232":"Baby Goods/Kids Goods",
     "2233":"Media/News/Publishing",
     "2234":"Bank/Financial Institution",
     "2235":"Non-Governmental Organization (NGO)",
     "2236":"Insurance Company",
     "2237":"Small Business",
     "2238":"Energy/Utility",
     "2239":"Retail and Consumer Merchandise",
     "2240":"Automobiles and Parts",
     "2241":"Industrials",
     "2242":"Transport/Freight",
     "2243":"Health/Medical/Pharmaceuticals",
     "2244":"Aerospace/Defense",
     "2245":"Mining/Materials",
     "2246":"Farming/Agriculture",
     "2247":"Chemicals",
     "2248":"Consulting/Business Services",
     "2249":"Legal/Law",
     "2250":"Education",
     "2251":"Engineering/Construction",
     "2252":"Food/Beverages",
     "2253":"Telecommunication",
     "2254":"Biotechnology",
     "2255":"Computers/Technology",
     "2256":"Internet/Software",
     "2258":"Travel/Leisure",
     "2260":"Community Organization",
     "2261":"Political Organization",
     "2262":"Vitamins/Supplements",
     "2263":"Drugs",
     "2264":"Church/Religious Organization",
     "2300":"Games/Toys",
     "2301":"App",
     "2500":"Local Business",
     "2501":"Hotel",
     "2503":"Landmark",
     "2505":"Transit Stop",
     "2506":"Airport",
     "2507":"Sports Venue",
     "2508":"Arts/Entertainment/Nightlife",
     "2509":"Automotive",
     "2510":"Spas/Beauty/Personal Care",
     "2511":"Event Planning/Event Services",
     "2512":"Bank/Financial Services",
     "2513":"Food/Grocery",
     "2514":"Health/Medical/Pharmacy",
     "2515":"Home Improvement",
     "2516":"Pet Services",
     "2517":"Professional Services",
     "2518":"Business Services",
     "2519":"Community/Government",
     "2520":"Real Estate",
     "2521":"Shopping/Retail",
     "2522":"Public Places",
     "2523":"Attractions/Things to Do",
     "2524":"Sports/Recreation/Activities",
     "2525":"Tours/Sightseeing",
     "2526":"Transportation",
     "2527":"Hospital/Clinic",
     "2528":"Museum/Art Gallery",
     "2600":"Organization",
     "2601":"School",
     "2602":"University",
     "2603":"Non-Profit Organization",
     "2604":"Government Organization",
     "2606":"Cause",
     "2618":"Political Party"
  }
```

**Comment by keitharm** [comment]
We will be adding this in the next major update :)

**Pull request closed without merging**
